# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('dj_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name=b'\xe6\x95\xb0\xe9\x87\x8f')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'\xe6\x80\xbb\xe4\xbb\xb7')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_user.UserInfo', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
    ]
