# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(default=b'', max_length=100)),
            ],
            options={
                'verbose_name': '\u5730\u5740\u4fe1\u606f',
                'verbose_name_plural': '\u5730\u5740\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('upwd', models.CharField(max_length=40, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('uemail', models.CharField(max_length=30, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('uphone', models.CharField(default=b'', max_length=11, verbose_name=b'\xe7\x94\xb5\xe8\xaf\x9d')),
                ('uyoubian', models.CharField(default=b'', max_length=6, verbose_name=b'\xe9\x82\xae\xe7\xbc\x96')),
                ('upeople', models.CharField(default=b'', max_length=10, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='addrinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_user.UserInfo'),
        ),
    ]
